### ISSUE TITLE
Blending recursive looping

### ISSUE THREAD

**Issue by bouguila** [StarcounterApps/Images#102] opened 2017-06-21 10:19 UTC
blending is getting into a recursive loop withing People app

### Steps to reproduce
1. Run following apps:
 . SignIn
 . People
 . Images
2. click on `Edit` for any existing person in People app.

### Expected result
only person partial handler should be invoked `("/people/partials/persons/{?}")`

### Actual result
organization handler is being invoked as well `("/people/partials/organizations/{?}")` causing odd behaviour

**Comment by warpech** [comment] 2017-06-21 20:52
Thank you for discovering the issue and a very good description. I believe that this needs a proper fix in `Blender.MapUri`. I have created an issue (linked above).

Anyway, I think that we can accept a workaround that will work with the current Starcounter.

**Comment by alemoi** [comment] 2017-06-22 13:06
Please specify which branches should be used and what Starcounter version.

**Comment by alemoi** [comment] 2017-06-22 13:29
Tried `master` on all 3 repos, with latest 2.3 Starcounter. When trying to go to http://127.0.0.1:8080/signin/user I get this in browser: 
![image](https://user-images.githubusercontent.com/208134/27436459-a1778044-575f-11e7-89ad-a3a0fc38fcf7.png)

**Comment by bouguila** [comment] 2017-06-22 13:36
signIn - master 
people - develop
images - develop
Starcounter version 2.3.0.6350

@alemoi i already merged the fix via a PR to Images app (on develop branch) so you might not get the error anymore

**Comment by alemoi** [comment] 2017-06-22 14:00
Thanks. Please provide this info next time, because I've spent some time trying develop and master. How can I reproduce the issue, if the fix is merged? Maybe I can get some branch of Images app?

**Comment by bouguila** [comment] 2017-06-22 14:23
@alemoi you can try with  Images - master, you still can reproduce the error there

**Comment by alemoi** [comment] 2017-06-22 14:57
As I see the Blending rules define the behavior. Here is the call sequence:
```
/people/partials/persons/c
/images/partials/somethings-edit/c
/people/partials/organizations/c
```

And here are the blending rules:
```
Blender.MapUri<Organization>("/people/partials/organizations/{?}");
Blender.MapUri<Organization>("/images/partials/somethings-edit/{?}");
Blender.MapUri<Person>("/images/partials/somethings-edit/{?}"); <--- this one is called first
```

So, these rules are declaring the behavior, which is correct. Can you please explain what is the issue with this?

**Comment by bouguila** [comment] 2017-06-22 15:05
when we trigger /People/partials/person-edit/{?} ,  /People/partials/organization-edit/{?} is invoked as well causing a null reference exception

**Comment by alemoi** [comment] 2017-06-22 15:18
Haven't seen the null reference exception but invocation of /People/partials/organization-edit/{?} is according to the rules above. Do you get  null reference during the Self.GET /People/partials/person-edit/{?}?

**Comment by bouguila** [comment] 2017-06-22 15:50
You have to click on edit for an existing person and then hit the save button

**Comment by alemoi** [comment] 2017-06-22 20:00
Yes, I did that and everything worked fine without null ref exc. Maybe its because I'm using 2.3.1 and the bug was fixed already? @bouguila can you please test with latest 2.3.1? Thanks!

**Comment by warpech** [comment] 2017-06-22 20:19
Git allows to find the parent commit from the time before the merge. GitHub exposes this information nicely.

These are the commits from before the merge:

-
 https://github.com/StarcounterApps/SignIn/commit/8c10b2f1c716bade691a33beee5128cff2a33618
-
 https://github.com/StarcounterApps/People/commit/a675e2fd0457355549a31a83bfe2a813b8a7b04d
-
 https://github.com/StarcounterApps/Images/commit/6dfcfce2989c62a51ee002c5622deb8e0d19ee8b

<img width="1440" alt="screen shot 2017-06-22 at 22 16 43" src="https://user-images.githubusercontent.com/566463/27454037-cdba298e-5798-11e7-9bc3-8a805413ba91.png">

**Comment by alemoi** [comment] 2017-06-22 20:25
Yes, however I think the fix might be on Starcounter side between 2.3.0 and 2.3.1.x

**Comment by alemoi** [comment] 2017-06-22 21:46
Guys, I'm having troubles understanding the problem here. I just tried to reproduce the problem in 2.3.0.x but its the same behaviour as with 2.3.1. I click Edit on some person in People app and I get this screen: 
![image](https://user-images.githubusercontent.com/208134/27457421-f676b192-57a4-11e7-8d97-1486020c0837.png)
- no infinite loop
- no null reference exception
- no errors in Chrome
- and all partials are called according to https://github.com/StarcounterApps/Images/issues/102#issuecomment-310405709

**Comment by bouguila** [comment] 2017-06-22 22:02
@alemoi The problem occurs when you hit Save

**Comment by alemoi** [comment] 2017-06-22 22:47
Great! Now I can finally get it. Will check tomorrow.

**Comment by alemoi** [comment] 2017-06-23 22:40
Thanks for the responses @bouguila The problem was identified: the blender was calling wrong handlers, of a different type with wrong object ID. For example, for person `FZ`:
```
/people/partials/persons/FZ
/images/partials/somethings-edit/FZ
/people/partials/organizations/FZ <--- this handler is wrongly called
```
I have produced a patch which is available this nightly. You can remove the fixes that you made temporary and check if everything works for you! Thank you!

**Comment by alemoi** [comment] 2017-06-25 21:04
I thought a lot about this on weekends and here is the deal.
The actual problem (that is exactly the same in this issue) can be described here:
```
Blender.MapUri<Organization>("/people/partials/organizations/{?}");
Blender.MapUri<Organization>("/images/partials/somethings-edit/{?}");
Blender.MapUri<Person>("/images/partials/somethings-edit/{?}");
```
So you see that both Person and Organization have images. Imagine now that `/images/partials/somethings-edit/{?}` is called containing Person as Id, let's say from `Self.GET`. Since we don't specify under which class, the `Self.GET` is made (Person or Organization), it can be the case that "/people/partials/organizations/{?}" is called with ID of the Person, which is totally wrong (should be Organization). I suppose this brings us to the discussion of context in `Self.GET` calls, right @warpech @bouguila ? https://github.com/Starcounter/RebelsLounge/issues/126
What about if `/images/partials/somethings-edit/{?}` is called from from the browser directly? Which object type it brings then?

There is no infinite loop problem, but a blending direction problem I suppose.
It also shows a problem of wrong blending in existing code: organisation should bring image, but image should not bring organisation. Therefore the direction parameters should be correct in `Blender.MapUri`

I'm thinking if there would be 3 handlers for images instead:
1. "/images/partials/person/somethings-edit/{?}"
2.  "/images/partials/organization/somethings-edit/{?}"
3.  "/images/partials/person/somethings-edit/{?}" <-- this one is general and Self.Only!
So the first 2 would call the third one which is Self.Only (not visible to the browser). Then contexts are not needed, and everything is clean, on a first glance.
If that would be the case than everything would work correctly (from the browser and self calls).
What do you think @warpech what don't you like in this case?

**Comment by alemoi** [comment] 2017-06-25 21:10
My proposal:
```
Blender.MapUri<Organization>("/people/partials/organizations/{?}");
Blender.MapUri<Organization>("/images/partials/organization-edit/{?}");
Blender.MapUri<Person>("/images/partials/person-edit/{?}");
```

**Comment by warpech** [comment] 2017-06-26 14:00
We are back to square one, because mapping same URI to multiple types was considered a feature of `Blender.MapUri`. See https://github.com/Starcounter/RebelsLounge/issues/126#issuecomment-309975374 and the following comment

But I agree that it won't work without some solution to the ambiguity.

In case of reverting this, please make sure to throw an error when trying to map the same URI twice. 

Also, please update the server-side blending page in the docs: https://docs.starcounter.io/guides/blending/blending/, which now mentions this as a feature (at the bottom).

**Comment by alemoi** [comment] 2017-06-27 10:33
@warpech i am not reverting this actually, just my last "fix" that just limited the Blending traverse. So, no changes will be added.

**Comment by alemoi** [comment] 2017-06-27 23:23
@bouguila can you please provide an indication of recursive looping because maybe I missed something.

**Comment by bouguila** [comment] 2017-06-28 08:00
cc @miyconst may have a better explanation of this issue

**Comment by miyconst** [comment] 2017-06-28 08:22
I think, @bouguila has made a wrong description. There is no recursive loop, the blending works as expected, if multiple URIs are mapped to the same token, all of them are called if one is triggered.

**Comment by alemoi** [comment] 2017-06-28 10:26
Thanks! Then I think I will close the issue, because I literally made 0 fixes. Please be more careful with issue description next time.

**Closed by alemoi** 2017-06-28 10:26 UTC
Labels: bug
